version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: shelf-postgres
    environment:
      POSTGRES_DB: shelf_audit
      POSTGRES_USER: shelf_user
      POSTGRES_PASSWORD: shelf_password
    ports:
      - "5432:5432"
    volumes:
      - shelf_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: shelf-rabbitmq
    ports:
      # ใช้พอร์ตมาตรฐานได้เลย เพราะโปรเจกต์เก่าใช้ 5673 ไปแล้ว จะไม่ชนกันแน่นอน
      - "5672:5672"   
      - "15672:15672"
    volumes:
      - shelf_rabbitmq_data:/var/lib/rabbitmq

volumes:
  shelf_postgres_data:
  shelf_rabbitmq_data:
